### ISSUE TITLE
ServiceManager runs OOM on circular dependency

### ISSUE THREAD

**Issue by pimjansen** [laminas/laminas-servicemanager#102] opened 2021-08-24 15:31 UTC
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 3.6.4

#### Summary

Creating a circular dependency will trigger an OOM instead of a catch.

#### Current behavior

The application runs OOM

#### How to reproduce

I do not have an exact code block but i can explain the scenario i am facing. I have an application which uses `Monolog` to write logs to disk. In the factory i am creating an `UserProcessor` which injects the current logged in user to the log.  To do this the factory uses the Laminas AuthenticationService to retrieve the user.

The problem is there that this service holds an alias. In basic setup this is not wrong however the factory that handles this is dependent on another service which depends on the logger. With this approach the logger has a dependency on the logger itself while constructing and is therefor in an endless loop. 

Result is an OOM

#### Expected behavior

Would be good if a circular dependency would be catching. Letting the app run OOM is always a bad thing

**Comment by boesing** [comment] 2021-08-24 15:49
We do have a cyclic alias check when the service manager is "configured".
Sadly, we do not have runtime checks for this.

One thing we need to keep in mind is that one can avoid cyclic dependencies when using lazy services. 
A potential bugfix should therefore address delegators - if any delegator factory is available for a service, the service manager should continue working as of now. Only if there is no delegator configured for that service,  a `CyclicDependencyException` should be thrown.

So this might be some kind of BC break as a new exception "could be thrown". But I am unsure if thats really a BC break if it ensures that the service manager does not run into an endless loop.

**Comment by pimjansen** [comment] 2021-08-24 16:00
Agree, in fact the issue i am facing is an architecture design gap. But an OOM is mostly not good for a servicemanager to happen on runtime so it could be a good addition to cap it on `x` loops and even make the loop count configurable for other strange usecases

**Comment by Ocramius** [comment] 2021-08-24 16:05
Unlikely meaningful: an OOM usually only happens if you have an infinite loop, so you should solve it during integration/acceptance testing level.

Any sort of runtime checks for these edge cases will hit hard on the performance of the ServiceManager, which is a no-go, given its critical path.

Alternatively, an architecture change (new major version) that does a dependency graph analysis is needed.

Closing as `won't fix` here: the behavior is expected, and up to the consumer to fix.

**Closed as completed by Ocramius** 2021-08-24 16:05 UTC
Labels: Bug, Won't Fix

**Comment by pimjansen** [comment] 2021-08-24 17:07
> Unlikely meaningful: an OOM usually only happens if you have an infinite loop, so you should solve it during integration/acceptance testing level.
> 
> 
> 
> Any sort of runtime checks for these edge cases will hit hard on the performance of the ServiceManager, which is a no-go, given its critical path.
> 
> 
> 
> Alternatively, an architecture change (new major version) that does a dependency graph analysis is needed.
> 
> 
> 
> Closing as `won't fix` here: the behavior is expected, and up to the consumer to fix.

Fine, @boesing asked me to raise this so

**Comment by boesing** [comment] 2021-08-24 17:13
I still think we could add a config flag to enable runtime circular dependency check which is disabled by default and thus would not be a BC break. Even tho it is up to the upstream project to fix the issue behind this, having some feedback in non-production environments would help finding the service which causes that infinite loop.

WDYT @Ocramius?

So in the end, this would be a feature request rather than a bug. The current behavior is definitely not a bug.

---

Even tho, determining if something is circular or not is quite tough due to the delegator logic but that probably could be addressed - but that wont be rock solid.

**Comment by Ocramius** [comment] 2021-08-24 18:42
IMO no - it's part of some pre-runtime analysis, and we discussed it in https://github.com/laminas/technical-steering-committee/issues/55 (see https://github.com/laminas/technical-steering-committee/blob/c7f6babfb1773d9cb9371208102cbb8b27980bd5/meetings/minutes/2021-03-01-TSC-Minutes.md#laminas-service-inspector ) /cc @zakirullin
