### ISSUE TITLE
Update psr/container

### ISSUE THREAD

**Issue by danielspk** [laminas/laminas-servicemanager#92] opened 2021-07-22 14:37 UTC
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes/no
| BC Break    | yes/no

#### Summary

Hi, is it possible to upgrade to `psr/container` version 2?

**Comment by Ocramius** [comment] 2021-07-22 14:40
See https://github.com/laminas/laminas-servicemanager/issues/18#issuecomment-879182790

**Comment by boesing** [comment] 2021-07-22 16:23
Yah, I dont think we can bump to new PSR major without replacing interop container. Having interop container replaced needs a ton of work which is not yet achievable. 

Maybe we can create some kind of roadmap on how we want to proceed. We need all components which are affected (which are plenty), we might need to find the most popular 3rd party components to push details to them on how to upgrade (if we want to do so), then we need to determine what kind of change/ we have to do and due to the fact that laminas always has a lack of using `final` we have to bump all of these components to new majors as well.

**Comment by Ocramius** [comment] 2021-07-22 16:30
Just spitballing, but container-interop could be polyfilled, meanwhile, for
compat.

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by boesing** [comment] 2021-07-22 21:52
Polyfilling while changing majors sounds too hacky tbh.

Even tho, by adding return typehints to `ContainerInterface::has` implementing classes would be a BC break as well. Or did I missunderstood your message?

**Comment by weierophinney** [comment] 2021-07-27 18:41
@boesing The idea is one I put forward a while back, but I think I may have run into an issue; need to review my notes.

The idea is this:

- Inline the container-interop interfaces into this package.
- Place a "replace" entry in the package indicating it replaces those interfaces (which means that any package or app installing laminas-servicemanager will no longer pull the original container-interop package, and any update operations to this new laminas-servicemanager version will _remove_ any previously installed container-interop package).

This then removes the need to install the container-interop package, while retaining BC for the current set of releases.

We would still need to do a new major to fully remove them and replace them with the PSR-11 interfaces, but at least our users would stop receiving the warnings.

Again, I need to review my notes and see what issues I ran into.

**Comment by boesing** [comment] 2021-07-27 18:52
@weierophinney So inlining the interfaces without changes just to avoid the "abandoned" message from composer? Or what would be the goal?

**Comment by weierophinney** [comment] 2021-07-27 20:45
Yes - that's the idea.

The problem we have currently is that all of the various FactoryInterface, AbstractFactoryInterface, DelegatorFactoryInterface, AbstractPluginManager, etc. all typehint on container-interop, which is what would require the major version bump. Most users do not directly extend those (many of the interfaces can use vanilla callables), so the primary concern is seeing that "container-interop is abandoned" message when they perform installs.

The other option is we do like we did going from v2 to v3, and create a separate set of interfaces that developers can opt-in to during v3 that typehint against PSR-11; with v4, we remove the old interfaces and only go forward with the new ones. The problem is, we've already done that once, so figuring out where they should live becomes more difficult.

The point @Ocramius makes is that we can address the concerns from the vocal majority quickly, and then buy time to do a proper migration later.

**Comment by dmetzler1988** [comment] 2021-12-13 14:00
I have the same case with the message "container-interop is abandoned" on multiple projects on install/update the composer dependencies.

**Comment by Ocramius** [comment] 2021-12-13 14:03
@dmetzler1988 yeah, can be safely ignored, and as you can see, we're working on it

**Comment by settermjd** [comment] 2022-03-21 08:23
Hey folks, as part of refactoring two packages, I need to refactor laminas-servicemanager to depend on psr/container 2.0. After reading this thread, I'd happily do the work to implement a PR, but I'll need some guidance to do so. If someone's up for that, I'm up to get it done. I think laminas-servicemanager is one of about 5 packages that I need to touch.

**Comment by Ocramius** [comment] 2022-03-21 08:28
@settermjd please see open PRs

**Comment by settermjd** [comment] 2022-03-21 10:15
Right you are. Sorry for not checking those before posting.

**Comment by Ocramius** [comment] 2022-03-21 11:15
No worries, just pointing you there: #96 is probably the most relevant one.

**Comment by brotkrueml** [comment] 2022-11-04 14:37
I am using the laminas-feed package for generating feeds in a TYPO3 extension. The laminas-feed package depends on laminas-servicemanager. Now the upcoming TYPO3 version requires psr/container in version 2 which conflicts with this package requirement of psr/container. So, is there a foresight when this package will be compatible with psr/container v2? By now, I only have the choice to abandon the usage of laminas-feed and look out for another package or postpone the compatibility with the next TYPO3 release in my extension.

**Comment by Ocramius** [comment] 2022-11-04 14:38
I'd say that we need to release a new major for that: no way around it, IMO.

That could also be the only BC break, TBH.

**Comment by drmax24** [comment] 2023-01-23 17:38
> 

Will a major verison will be released any time soon? Some packages already require psr2 and stuck unupdated.
You can't marinade it forever...

**Comment by weierophinney** [comment] 2023-01-23 17:51
> Will a major verison will be released any time soon?

It's in progress. We discussed a plan of action during the last steering committee meeting, and @boesing is leading the effort. It will take a while to roll out, but this package will be the first, while the MVC and likely Mezzio will be last to get support (we have to ensure all the various packages on which they depend that ALSO depend on this package are released first).

You'll see some progress on this in the coming weeks.

**Comment by boesing** [comment] 2023-05-02 19:32
Closed by #188

**Closed as completed by boesing** 2023-05-02 19:32 UTC
Labels: BC Break, Enhancement
