### ISSUE TITLE
Package container-interop/container-interop is abandoned

### ISSUE THREAD

**Issue by spbentz** [laminas/laminas-servicemanager#109] opened 2021-11-10 08:00 UTC
### BC Break Report

|    Q            |   A
|------------ | ------
| Version      |  3.10.0

#### Summary

Composer install returns:
"Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead."

**Comment by Ocramius** [comment] 2021-11-10 08:26
Duplicate of https://github.com/laminas/laminas-servicemanager/pull/96

**Closed as completed by Ocramius** 2021-11-10 08:26 UTC
Labels: Duplicate
