### ISSUE TITLE
`ContainerInterface` reference was changed in a minor release

### ISSUE THREAD

**Issue by fabiang** [laminas/laminas-servicemanager#59] opened 2020-12-01 12:51 UTC
### BC Break Report

|    Q        |   A
|------------ | ------
| Version     | 3.5.0

#### Summary

I waited for this day since two years or so, but did not expect this to happen on a minor release. Is it intentional that the `Laminas\ServiceManager\Factory\FactoryInterface` now uses `Psr\Container\ContainerInterface` instead of `Interop\Container\ContainerInterface` and all my factories are broken now, while I've only updated to minor version 3.5.0? Not even a single word in the changelogs. Shouldn't such a small change with huge impact be done in the 4.0 release?

Can we have an upgrade guide please?

**Comment by Ocramius** [comment] 2020-12-01 13:06
@fabiang hmm, no, a BC break was not expected.

I did a release due to `3.5.0` being ready to be released and all changes merged thus far: sorry if it caused any issue: means that we have to get better at handling BC.

As for the BC break, since it was released minutes ago, I'd go with `3.5.1` that reverts it.

**Comment by Ocramius** [comment] 2020-12-01 13:10
Indeed, `3.5.0` contained commits that should not have been there: I'm preparing a patch and will crank out a release ASAP

**Comment by Ocramius** [comment] 2020-12-01 13:24
Ok, so here's what happened:

 1. I merged zendframework/zend-servicemanager#187 into `develop` 2 years ago: https://github.com/zendframework/zend-servicemanager/pull/187#issuecomment-364758559
 2. package got renamed
 3. at some point, `develop` became `3.5.x` instead of becoming `4.0.x`
 4. today, after reading a ping (https://github.com/laminas/laminas-servicemanager/pull/57#issuecomment-736345032) and checking the issues that were assigned to the `3.5.0` milestone (https://github.com/laminas/laminas-servicemanager/milestone/1?closed=1) I triggered the release automation (https://github.com/laminas/laminas-servicemanager/actions/runs/393759253)

The problem is that the diff (https://github.com/laminas/laminas-servicemanager/compare/3.4.1..3.5.0) does not match the milestone (https://github.com/laminas/laminas-servicemanager/milestone/1?closed=1)

**Comment by Ocramius** [comment] 2020-12-01 13:29
Ok, after evaluating the entire diff, a full revert of 3.5.0 is needed: I will push `3.4.1` as `3.5.1` and move `3.5.x` to `4.0.x`, and `3.4.x` as `3.5.x`

**Comment by Ocramius** [comment] 2020-12-01 13:40
Marking this as closed and starting `3.5.1` release automation

**Closed as completed by Ocramius** 2020-12-01 13:40 UTC
Labels: BC Break, Bug

**Comment by Ocramius** [comment] 2020-12-01 13:44
`3.5.1` is now the same as `3.4.1`

I will publish `3.5.0` as a new branch, mostly for us to move things into `4.0.x`.

**Comment by fabiang** [comment] 2020-12-01 13:49
Thanks a lot. I can confirm that it's working with 3.5.1 again.

Would you accept an PR with an unit tests for this interface? I would do it with Prophecy, so we can make sure that such an fundamental interface is always correct for that version?

**Comment by Ocramius** [comment] 2020-12-01 13:54
@fabiang the tests are already in place: the diffs changed all related tests too, hence why it looked like everything was ready for a release (and wasn't).

What should probably be built in is something like `roave/backward-compatibility-check`, which guarantees that a minor release won't contain more backwards-incompatible changes (https://github.com/Roave/BackwardCompatibilityCheck).

Can you perhaps send a patch with that? See https://github.com/Roave/BackwardCompatibilityCheck/blob/20c0e653865822ecf836bd249810dea8f677a864/.github/workflows/backwards-compatibility.yml for an example of how this works there.

**Comment by fabiang** [comment] 2020-12-01 14:01
Btw I think 3.5.0 should be removed from Packagist.org. If someone does `compose require laminas/laminas-service` right now he will get `^3.5` in his `composer.json`, but 3.5.1 is installed. When he executed his tests with `composer install --prefer-lowest` (I do often to check the lowest versions required) the tests will break.

**Comment by Ocramius** [comment] 2020-12-01 14:07
Packagist does scrub versions after some time: happens overnight though.

Alternatively, @weierophinney can "press zeh button" when online.

**Comment by weierophinney** [comment] 2020-12-01 14:25
Done!

**Comment by adamturcsan** [comment] 2020-12-01 14:39
Thanks for the fast reaction! I've hit the 3.5.0, but it's all good now!

**Comment by fabiang** [comment] 2020-12-02 10:18
> What should probably be built in is something like `roave/backward-compatibility-check`, [...]

I've tried. But I can't install any version without needing to update other requie-devs and then loosing PHP support for <7.x.

**Comment by Ocramius** [comment] 2020-12-02 10:46
The tool can be installed independently in a job that runs 7.4

**Comment by PowerKiKi** [comment] 2020-12-08 05:39
According to #51, the 3.5.0 version should have brought support for PHP 8.0. But with the cancellation of 3.5.0 and complete revert in 3.5.1, we lost that PHP 8.0 support.

I see there is already a [3.5.2 milestone](https://github.com/laminas/laminas-servicemanager/milestone/6). Is it planned to (re-)release the non-breaking parts from 3.5.0 as a 3.5.2 ? should we open pull requests for that ? or what should we do ?

**Comment by froschdesign** [comment] 2020-12-08 07:23
@PowerKiKi 
Please have a look at #64

**Comment by PowerKiKi** [comment] 2020-12-08 07:30
Thanks ! so I will wait for 3.6.0 for PHP 8

**Comment by mrVrAlex** [comment] 2021-02-03 12:06
FYI: IMHO: This problem with BC Break can be resolve just like this: 
```php
use interop\container\containerinterface as OldContainerInterface;
use Psr\Container\ContainerInterface;

class_alias(ContainerInterface::class, OldContainerInterface::class);
```
And add this file to composer autoload...

P.S.  It's ugly but it worked for 3.5.0 version for me.)

**Comment by boesing** [comment] 2021-02-03 20:48
@shandyDev We reverted 3.5.0 and thus you should upgrade to 3.6.X if you are still using 3.5.0.
