### ISSUE TITLE
Cannot declare interface Interop\Container\Exception\NotFoundException, because the name is already in use

### ISSUE THREAD

**Issue by starred-gijs** [laminas/laminas-servicemanager#128] opened 2022-04-25 15:15 UTC
### BC Break Report

|    Q        |   A
|------------ | ------
| Version     | 3.11
| PHP-FPM with opcache.preload enabled | 8.1.4
| Symfony  (with Runtime) | 5.4.7

#### Summary
After upgrading to version 3.11 Im getting all these E_WARNING messages in my logs and monitoring tools.  Im using Symfony 5.4 and FPM with opcache.preload enabled. When I disable preload the warning goes away. 

```
E_WARNING: Cannot declare interface Interop\Container\Containerinterface, because the name is already in use
in class_alias called at /app/vendor/laminas/laminas-servicemanager/src/autoload.php (13)
in require called at /app/vendor/composer/autoload_real.php (55)
in composerRequire6635dcbc130fab9e00890c611d69ace8 called at /app/vendor/composer/autoload_real.php (38)
in ComposerAutoloaderInit6635dcbc130fab9e00890c611d69ace8::getLoader called at /app/vendor/autoload.php (12)
in require_once called at /app/vendor/autoload_runtime.php (5)
in require_once called at /app/public/index.php (9)
```
And also for line 14/15 I get the warning about ContainerException/NotFoundException.

By upgrading to version 3.11 the Interop package got removed. I have no other references to Interop in my generated preload files or any other place. I think its related to opcache.preload, but im not sure.

In a previous version of the src/autoload.php file, there was an `class_exists` check before the alias:
https://github.com/laminas/laminas-servicemanager/commit/0732d65c14962d4aa25c78788cae5bb0a4ac537f#diff-984b8e3111197dd008894b4b1575ffcbda5c801cb8857434cc2898b5dca67873R13

But when I use that version, the warning is still present. 

Downgrading to 3.10.* resolves the issue.

**Comment by Ocramius** [comment] 2022-04-25 15:23
Duplicate of #124.

`ext-psr` is not compatible with the last version of this package, as declared in `composer.json`.

**Comment by Ocramius** [comment] 2022-04-25 15:25
Sorry, my mistake: seems like a completely different problem, and multitasking got me 🤦

**Comment by Ocramius** [comment] 2022-04-25 15:26
Does the crash manifest itself without preloading?

**Comment by starred-gijs** [comment] 2022-04-25 15:31
No worries.  I never heard of that psr extension, and I just double checked our php setup, its definitely not there. 

When I disable opcache.preload the error is gone

**Comment by Ocramius** [comment] 2022-04-26 12:10
I think the eager autoloading configuration that we have in `composer.json` may be the issue here: 

https://github.com/laminas/laminas-servicemanager/blob/3.11.2/composer.json#L68

I guess we could check their existence here: https://github.com/laminas/laminas-servicemanager/blob/3.11.2/src/autoload.php#L13

A bit worried if the preloader picked up another class elsewhere though. Also unsure how to test this to prevent regressions 🤔

**Comment by starred-gijs** [comment] 2022-04-26 13:00
> In a previous version of the src/autoload.php file, there was an `class_exists` check before the alias:
> [0732d65#diff-984b8e3111197dd008894b4b1575ffcbda5c801cb8857434cc2898b5dca67873R13](https://github.com/laminas/laminas-servicemanager/commit/0732d65c14962d4aa25c78788cae5bb0a4ac537f#diff-984b8e3111197dd008894b4b1575ffcbda5c801cb8857434cc2898b5dca67873R13)

Yesterday changed my local version of that file with `class_exists` checks, but failed to realise these are actually interfaces. I just checked again but with `interface_exists` checks and now the issue is done. I looked at some other autoload files like polyfill and I see that all of them have checks eg https://github.com/symfony/polyfill/blob/v1.25.0/src/Apcu/bootstrap.php#L75

I can make a PR shortly

**Comment by Ocramius** [comment] 2022-04-26 13:04
That seems sensible: the difficult part is the test 😁

**Comment by starred-gijs** [comment] 2022-04-26 13:12
> the difficult part is the test 😁

Yes I agree that will be difficult, because of the all the prerequisites that will show this error. Im not sure that will be worth the trouble.

**Comment by LucasHantz** [comment] 2022-06-28 15:19
Why was the MR #129 closed?
As stated in this tweet answered by Nikic relating to the issue of the class_alias they should be conditional as all other libraries did this change. https://mobile.twitter.com/nikita_ppv/status/1208025415253659648

Please make this change to avoid warning in project that depends on other laminas libraries.

**Comment by Ocramius** [comment] 2022-06-28 15:26
@LucasHantz I think @starred-gijs deleted their repository? Github is not saying why the PR was closed, or who did it, but interestingly, your mention comes **before** the deletion event, according to Github itself :thinking: 

Anyway, if you feel like it is necessary, please open a new patch (can take same commits, if needed).

**Comment by boesing** [comment] 2022-06-28 16:02
We need to find out if the `class_alias` made by whatever library is actually the same alias we are expecting it to be.

Because one can also point `container-interop` via `class_alias` to any other interface which is compliant with PSR-11 and thus must not currently be `Psr\Container\ContainerInterface`, etc.

So this works perfectly but that will break applications if they expect that to be a PSR-11 interface from within the `Psr\Container` namespace:

```php

interface RandomPsr11ContainerInterface
{
    public function get($foo);
    public function has($foo);
}

class_alias(RandomPsr11ContainerInterface::class, '\Interop\Container\ContainerInterface');
```

That is why we removed the conditional here because there should be no1 else to `class_alias` container-interop.

@LucasHantz Do you have a link to libraries which currently use `class_alias` to replace `container-interop`? Just to have some more investigations here. I see a problem when there are multiple libraries replacing the same interface. Because in our case, we explicitly want to set that alias to keep BC compatibilty within factories, etc. which might not be 100% fulfilled if we just use `interface_exists`.

**Comment by starred-gijs** [comment] 2022-06-29 07:44
I deleted the repo and the PR was closed. I re-created the PR to help the discussion.

**Closed as completed** 2022-06-29 08:01 UTC
Labels: Bug, Enhancement
